---
title: "MLB 2017"
author: "Jensen Holm & Kyle Knapp"
date: "2022-11-07"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Libraries
```{r include=TRUE, message=FALSE, warning=FALSE}
library(png)
library(grid)
library(tidyverse)
library(boot)
```


## Read in the data
```{r include = TRUE}

dataFilePath <- str_c(getwd(), "/data/", sep = "")

importCSV <- function(fileName) {
  read.csv(str_c(dataFilePath, str_c(fileName, ".csv", sep = ""), sep = ""))
}

statCast <- importCSV("statcast2017")
bbref <- importCSV("bbref2017")

# purpose of the trackman data is so that we can do a lubridate function with dates
trackman <- importCSV("trackman")

```


## Joining the two datasets together with dplyr and stringr
```{r include=TRUE}
# str_c() is a stirngr function
statCastName <- statCast %>% mutate(
  Name = str_c(
    str_replace_all(first_name, " ", ""), 
    str_replace_all(last_name, " ", ""), 
    sep = " ")
)  

bsbl <- left_join(
  statCastName, 
  bbref, 
  by = "Name"
)
```


## EDA

```{r}
glimpse(bsbl)
```



```{r include = TRUE, warning=FALSE, message=FALSE}
# without applying this filter on the data set, there were
# a lot of players with too few plate appearances messing 
bsblSub <- bsbl %>% subset(attempts > 100)  

bsblSub %>% ggplot(aes(
  x = anglesweetspotpercent, 
  y = avg_distance, 
  color = attempts, 
  alpha = 0.5)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(
    title = "Average Hit Distance as a funciton of launch angle sweet spot %" ,
    x = "Launch Angle Sweet Spot %",
    y = "Average Hit Distance (ft.)"
  )
```

```{r, include=TRUE, message=FALSE, warning=FALSE}
# plot batting average by average exit velocity, something that I could not do without
# having mergeed the datasets

bsblSub %>% ggplot(aes(
  x = BA, 
  y = avg_hit_speed, 
  color = barrels, 
  alpha = 0.5)) + 
  geom_point() +
  geom_smooth(method = "lm") + 
  labs (
    title = "Average Hit Speed as a function of Batting Average",
    x = "Batting Average",
    y = "Average Hit Speed"
  )
```


# plotting average hit circle
```{r include = TRUE}

# read in baseball field image
imgPath <- str_c("img", dataFilePath, sep = "")
img <- png::readPNG(system.file(imgPath, package = "png"))

```



## T-Test between the Colorado Rockies Average hit speed and the rest of the MLB
```{r}
# t test
colorado <- bsbl %>% subset(Team == "Colorado")
everyoneElse <- bsbl %>% subset(Team != "Colorado")

t.test(
  colorado$avg_hit_speed, 
  everyoneElse$avg_hit_speed
)
```

# Non-Parametric BootStrap
```{r include=TRUE, message=FALSE, warning=FALSE}
bsbl2 <- na.omit(bsbl)

set.seed(10)

x <- c(bsbl2$H)

#define function to calculate mean
meanFunc <- function(x,i){mean(x[i])}

#calculate standard error using 100 bootstrapped samples
boot(x, meanFunc, 100)

bsbl2 %>% ggplot(aes(x = H)) + 
 geom_histogram()
```

# Parametric BootStrap
```{r include=TRUE}
# Number of bootstrap samples
B <- 100

# Instantiating matrix for bootstrap samples
paramBoots <- matrix(NA, 
                     nrow = length(bsbl2), 
                     ncol = B
)

# Sampling with replacement B times
for(b in 1:B) {
paramBoots[, b] <- rnorm(
  n = length(bsbl2), 
  mean = mean(bsbl2$H), 
  sd = sd(bsbl2$H)
  )
}

paramBootMedians <- vector(length = B)
for(a in 1:B){
 paramBootMedians[a] <- mean(paramBoots[,a])
}

sd(paramBootMedians)
```


# pivoting the data into wide format
```{r include=TRUE}

for (team in unique(bsblSub$Team)) {
  print(team)
}

```

