---
title: "Baseball Dashboard"
author: Kyle Knapp and Jensen Holm
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(flextable)
library(readr) 

set.seed(1994)
```

```{r, include = FALSE, eval = TRUE}
# Importing CSV file
statCast <- read_csv("statcast2017.csv")

bbref<- read_csv("bbref2017.csv")

statCastName <- statCast %>% mutate(Name = paste(str_replace_all(first_name, " ", ""), str_replace_all(last_name, " ", ""), sep = " "))  

bsbl <- left_join(statCastName, bbref, by = "Name")

bsblSub <- bsbl %>% subset(attempts > 100)  

### Summary table

# Team summaries of Barrels

bsbl <- na.omit(bsbl)
bsbl5 <- bsbl[!grepl(",", bsbl$Team),]

teamSummary <- bsbl5 %>% group_by(Team) %>% 
   summarise(Average = mean(barrels, na.rm = TRUE),
             Median = median(barrels, na.rm = TRUE),
             Min = min(barrels, na.rm = TRUE),
             Max = max(barrels, na.rm = TRUE)) %>%
  mutate(across(Average:Max, ~ round(.x, 3))) %>% 
  arrange(desc(Average))

```

```{r}
# Creating bar chart
avg_age <- bsbl %>% group_by(Team) %>% 
  summarize(mean_age = mean(Age, na.rm = T))

avg_age2 <- avg_age[!grepl(",", avg_age$Team),]
avg_age2 <- avg_age2[-28,]

age_bar <- avg_age2 %>% ggplot(aes(x = Team, y = mean_age, color = Team)) +
  geom_col() +
   labs(title = "Average Age of Every MLB Team",
       x = "Team",
       y = "Average Age",
       caption = "data source: Baseball Reference") +
  scale_fill_manual(values = c("#D55E00","#0072B2")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = .7),
        legend.position = "none")
```

```{r}
density <- bsblSub %>% ggplot(aes(x = HR, y = RBI)) + geom_density_2d_filled() +
  labs(title = "Runs Batted In as a function of Home Runs in 2017 (Density Plot)")
```



Row {data-height=650}
-------------------------------------

### Density plot of Home Runs vs RBIs

```{r}
density
```

Row {data-height=350}
-------------------------------------
   
### Average Age of Every MLB Team

```{r}
age_bar
```   
    
### Summary Statistics of Number of Barrels per Team

```{r}
teamSummary %>% flextable::flextable()
```